### ISSUE TITLE
class nn.OneHot has been already assigned a parent class

### ISSUE THREAD

**Issue by jamiechoi1995** [doubledaibo/clcaption_nips2017#1]
wcai@tdtd-desktop ~/git/clcaption_nips2017 $ th cl_train_cross.lua
/home/wcai/torch/install/bin/luajit: /home/wcai/torch/install/share/lua/5.1/trepl/init.lua:389: /home/wcai/torch/install/share/lua/5.1/trepl/init.lua:389: /home/wcai/torch/install/share/lua/5.1/torch/init.lua:102: class nn.OneHot has been already assigned a parent class

stack traceback:
        [C]: in function 'error'
        /home/wcai/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        cl_train_cross.lua:11: in main chunk
        [C]: in function 'dofile'
        ...wcai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d80

I am new to torch, did I miss any package for running this code?Thanks.

**Comment by doubledaibo** [comment]
In this case, just delete the file.

**Comment by jamiechoi1995** [comment]
I deleted the file, then torch reminds me that I lacks of the package 'trepl'.

But after I install that package, the file will be automatically created again, and this issue happen happens again.

And if I deleted the file again, then torch reminds me that I lacks of the package 'trepl' again.

Seems it falls into a loop.


wcai@tdtd-desktop ~/git/clcaption_nips2017 $ rm /home/wcai/torch/install/share/lua/5.1/trepl/init.lua
wcai@tdtd-desktop ~/git/clcaption_nips2017 $ th cl_train_cross.lua
/home/wcai/torch/install/bin/luajit: ...wcai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:104: module 'trepl' not found:Failed loading module trepl in LuaRocks rock trepl scm-1
        no field package.preload['trepl']
        no file '/home/wcai/.luarocks/share/lua/5.1/trepl.lua'
        no file '/home/wcai/.luarocks/share/lua/5.1/trepl/init.lua'
        no file '/home/wcai/torch/install/share/lua/5.1/trepl.lua'
        no file '/home/wcai/torch/install/share/lua/5.1/trepl/init.lua'
        no file './trepl.lua'
        no file '/home/wcai/torch/install/share/luajit-2.1.0-beta1/trepl.lua'
        no file '/usr/local/share/lua/5.1/trepl.lua'
        no file '/usr/local/share/lua/5.1/trepl/init.lua'
        no file '/home/wcai/.luarocks/lib/lua/5.1/trepl.so'
        no file '/home/wcai/torch/install/lib/lua/5.1/trepl.so'
        no file '/home/wcai/torch/install/lib/trepl.so'
        no file './trepl.so'
        no file '/usr/local/lib/lua/5.1/trepl.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...wcai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:104: in main chunk
        [C]: at 0x00405d80
wcai@tdtd-desktop ~/git/clcaption_nips2017 $ luarocks install trepl
Installing https://raw.githubusercontent.com/torch/rocks/master/trepl-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/trepl-scm-1.rockspec... switching to 'build' mode
Cloning into 'trepl'...
remote: Counting objects: 18, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 18 (delta 1), reused 10 (delta 0), pack-reused 0
Receiving objects: 100% (18/18), 16.73 KiB | 3.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
gcc -O2 -fPIC -I/home/wcai/torch/install/include -c utils.c -o utils.o
gcc -shared -o treplutils.so -L/home/wcai/torch/install/lib utils.o
gcc -O2 -fPIC -I/home/wcai/torch/install/include -c readline.c -o readline.o
gcc -shared -o readline.so -L/home/wcai/torch/install/lib readline.o -lreadline
Updating manifest for /home/wcai/torch/install/lib/luarocks/rocks
trepl scm-1 is now built and installed in /home/wcai/torch/install/ (license: BSD)

wcai@tdtd-desktop ~/git/clcaption_nips2017 $ echo $?
0
wcai@tdtd-desktop ~/git/clcaption_nips2017 $ th cl_train_cross.lua
/home/wcai/torch/install/bin/luajit: /home/wcai/torch/install/share/lua/5.1/trepl/init.lua:389: /home/wcai/torch/install/share/lua/5.1/trepl/init.lua:389: /home/wcai/torch/install/share/lua/5.1/torch/init.lua:102: class nn.OneHot has been already assigned a parent class

stack traceback:
        [C]: in function 'error'
        /home/wcai/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        cl_train_cross.lua:11: in main chunk
        [C]: in function 'dofile'
        ...wcai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d80

**Comment by doubledaibo** [comment]
did you comment out https://github.com/doubledaibo/clcaption_nips2017/blob/9d77f5d054505dac414a7f70986303e305d943f7/misc/cl_adaptiveattention.lua#L98 ?

**Comment by jamiechoi1995** [comment]
Issue still remains after I comment that line.

wcai@tdtd-desktop ~/git/clcaption_nips2017 $ sed -n '98p' misc/cl_adaptiveattention.lua
-- require 'misc.OneHot'
wcai@tdtd-desktop ~/git/clcaption_nips2017 $ th cl_train_cross.lua              /home/wcai/torch/install/bin/luajit: /home/wcai/torch/install/share/lua/5.1/trepl/init.lua:389: /home/wcai/torch/install/share/lua/5.1/trepl/init.lua:389: /home/wcai/torch/install/share/lua/5.1/torch/init.lua:102: class nn.OneHot has been already assigned a parent class

stack traceback:
        [C]: in function 'error'
        /home/wcai/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        cl_train_cross.lua:11: in main chunk
        [C]: in function 'dofile'
        ...wcai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d80

**Comment by doubledaibo** [comment]
you can read the error message. you are using cl_train_cross.lua, so you should comment the same line in cl_cross.lua
